#!/bin/bash

# Utils to make commit in short way

DEFAULT_VERSION_CMD="git"
ARC_VERSION_CMD="arc"
VERSION_CMD="git"
SEPARATOR=": "

EXECUTION_CMD_SVC=""

get_error() {
    echo "The variable $1 is not defined."
}

set_exection_cmd_svc() {
    if [ -z "$VERSION_CMD" ]; then
        echo get_error "VERSION_CMD"
        exit 0
    fi

    if [ -z "$SEPARATOR" ]; then
        echo get_error "SEPARATOR"
        exit 0
    fi

    case $VERSION_CMD in
        $ARC_VERSION_CMD)
            EXECUTION_CMD_SVC+=$ARC_VERSION_CMD
            ;;
        *)
            EXECUTION_CMD_SVC+=$DEFAULT_VERSION_CMD
            ;;
    esac
}

update_execution_cmd() {
    EXECUTION_CMD_BEFORE_HOOK="add ."
    EXECUTION_CMD="commit -m "
    EXECUTION_CMD_AFTER_HOOK="status"
}

set_exection_cmd_svc
update_execution_cmd

commit_msg_fn() {
    status_msg=( $($EXECUTION_CMD_SVC status | head -1) )
    branch_name="${status_msg[@]: -1:1}"

    commit_msg=""
    commit_msg+=$branch_name
    commit_msg+=$SEPARATOR
    commit_msg+=$@

    EXECUTION_CMD+=\"${commit_msg}\"
   
    eval "$EXECUTION_CMD_SVC $EXECUTION_CMD_BEFORE_HOOK"
    eval "$EXECUTION_CMD_SVC $EXECUTION_CMD"
    eval "$EXECUTION_CMD_SVC $EXECUTION_CMD_AFTER_HOOK"
}

#alias commit="commit_msg_fn"
